name: astrointeractives
channels:
  - conda-forge
dependencies:
  - astropy
  - bqplot
  - jupyter
  - matplotlib
  - pandas
  - scipy
  - ipysheet
  - ipywidgets>=8.0
  - numpy>=1.13 
  - pythreejs>=1.0.0
  - voila>=0.5.6
